
function filterGeneratedFiles {
  for f in $@; do
    head -n2 $f | grep -qE '// Code generated by' || echo $f
  done
}

function filterExcludedFiles {
  CHECK=`echo "$CHECK" \
		| grep -v "^\.git/" \
          | grep -v "^\.gitignore" \
		| grep -v "^\.build/" \
		| grep -v "^vendor/" \
          | grep -v "^Makefile" \
		| grep -v "testdata/" \
		| grep -v "^LICENSE$" \
		| grep -v "\.gen\.go$" \
		| grep -v "^Gopkg\.lock$" \
		| grep -v "\.md$" \
		| grep -v "ci.properties" \
		| sort -u`

  CHECK=$(filterGeneratedFiles "$CHECK")
}

CHECK=$(git ls-files)
filterExcludedFiles

if [[ -z "$CHECK" ]]; then
   echo "All files are excluded from having license headers"
   exit 0
fi

missing=`echo "$CHECK" | xargs ls -d 2>/dev/null | xargs grep -L -E "Copyright 2019 The bottle Authors|Copyright 2015 The go-ethereum Authors"`
echo $missing
if [[ -z "$missing" ]]; then
   echo "All files have GNU Lesser General Public License headers"
   exit 0
fi
echo "The following files are missing GNU Lesser General Public License headers:"
echo "$missing"
echo
echo "Please replace the header comment text with:"
echo "// Copyright 2019 The bottle Authors
// This file is part of the bottle library.
//
// The bottle library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The bottle library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the bottle library. If not, see <http://www.gnu.org/licenses/>."

echo
echo "Checking committed files for GNU Lesser General Public License headers ..."
missing=`echo "$missing" | xargs ls -d 2>/dev/null | xargs grep -L "http://www.gnu.org/licenses/"`
if [[ -z "$missing" ]]; then
   echo "All remaining files have Apache 2.0 headers"
   exit 0
fi
echo "The following files are missing headers:"
echo "$missing"
echo "Fatal Error - All files must have a license header"
exit 1